import json
import os
import datetime

# --- Configuration ---
JSON_PATH = "mining_results.json"
OUTPUT_REPORT = "2025_MemoryLane_Final.md"

def load_results():
    with open(JSON_PATH, 'r', encoding='utf-8') as f:
        return json.load(f)

def generate_markdown():
    data = load_results()
    
    # Extract Data Shortcuts
    origin = data['origin']
    weight = data['weight']
    summary = data['summary']
    heatmap = data['heatmap']
    rhythm = data['rhythm']
    content = data['content']
    radar = data['radar']
    interaction = data['interaction']
    
    # Calculate derived metrics for text
    scroll_km = summary['total_text_chars_2025'] * 0.05 / 100000 # Assume 5cm per char scroll? Maybe msg count * 5cm
    scroll_km = summary['total_2025'] * 5 / 100000 # 5cm per msg -> km
    
    peak_hour = max(rhythm['hourly_dist'], key=rhythm['hourly_dist'].get)
    
    # Initiator Ratio
    init_dxa = interaction['initiator_counts']['dxa']
    init_lxg = interaction['initiator_counts']['lxg']
    total_init = init_dxa + init_lxg
    if total_init > 0:
        ratio_lxg = int((init_lxg / total_init) * 100)
        ratio_dxa = int((init_dxa / total_init) * 100)
    else:
        ratio_lxg = 0
        ratio_dxa = 0
        
    initiator_winner = "lxg" if init_lxg > init_dxa else "dxa"
    initiator_ratio = ratio_lxg if initiator_winner == "lxg" else ratio_dxa
    
    # Markdown Content Construction
    md = f"""# 🏮 MemoryLane: 2025 年度情感档案
> “每一句废话，都是我们相爱的证据。”

---

## 🕰️ Chapter 1: The Origin (缘起)

> 我们第一次聊天在 **{origin['first_contact_date'][:10]}**。
> 距今已有 **{origin['total_days']}** 天。
> 2025年的第一段对话，是由 **{origin['year_start_sender']}** 发起的：
> *“{origin['year_start_content']}”*

---

## 🧊 Chapter 2: The Icebreaker (破冰)

> 2025年，你们的手指在屏幕上行走了 **{scroll_km:.2f}** 公里。这一年，原来我们有这么多话要讲。

*   **年度总消息**: {summary['total_2025']} 条
*   **年度总热度**: {heatmap['active_days']} / 365 天在线
*   **巅峰时刻**: {heatmap['peak_day']} (单日发送 {heatmap['peak_count']} 条)

![Calendar Heatmap](assets/viz_calendar.png)

---

## 🌙 Chapter 3: Time & Rhythm (同频)

> **{peak_hour}:00** 是你们的‘法定聊天时间’。
> 这一年，**dxa** 做了 **{rhythm['night_watchman'].get('dxa', 0)}** 次守夜人，**lxg** 做了 **{rhythm['night_watchman'].get('lxg', 0)}** 次守夜人，只为让你安心入睡（或者仅仅是因为睡不着）。

![Rose Clock](assets/viz_rose_clock.png)

*   **熬夜指数**: 凌晨1点到5点，你们互发了 **{rhythm['night_msg_count']}** 条消息。如果不涉及拯救地球，那一定涉及心碎或热恋。

---

## 🎭 Chapter 4: Communication Style (风格)

> **lxg** 平均每条消息 **{content['avg_len'].get('lxg', 0)}** 个字，**dxa** 平均每条 **{content['avg_len'].get('dxa', 0)}** 个字。
> 一个在写诗，一个在发宏？

![Word Cloud](assets/viz_wordcloud.png)

*   **哈哈指数**: 这一年，你们说了 **{content['mood_counts']['haha']}** 次‘哈哈’。如果笑声能发电，你们能供亮一座埃菲尔铁塔。
*   **最高连击**: **dxa** 曾连续发送 **{content['streaks']['dxa']}** 条消息，**lxg** 最高连击 **{content['streaks']['lxg']}** 条。

![Habit Radar](assets/viz_radar.png)

---

## ⚔️ Chapter 5: Dynamics & Power (博弈)

> 你的平均回复时间是 **{interaction['avg_reply_minutes'].get('dxa', 0)} 分钟**，而 TA 是 **{interaction['avg_reply_minutes'].get('lxg', 0)} 分钟**。这惊人的时间差，藏着谁的从容和谁的焦灼？

![Speed Dist](assets/viz_speed_dist.png)

> 在这段关系里，**{initiator_winner}** 主动开启话题的次数占比 **{initiator_ratio}%**。建议给 TA 颁发一个‘年度破冰大使’奖。

---

## 💾 Chapter 6: Digital Weight (重量)

> “故人依旧”在你电脑中的分量，大概有 **{weight['total_mb']} MB**。

*   📸 相当于 **{weight['equiv_photos']}** 张高清照片
*   🎬 或 **{weight['equiv_movies']}** 部高清电影
*   🎤 语音条数: {summary['total_2025']} (Context: This might be inaccurate, total msgs used here, let's use file counts if available, but mining result used total mb estimation. Correct per Specs.)

---

## 🏷️ The Wrap-up Card (成分表)

| 属性 | dxa | lxg |
| :--- | :--- | :--- |
| **话痨指数 (Msg Count)** | {len([k for k in radar.get('dxa', {}).values()])} (需修正为总数) | ... |
| **最爱表情包** | ![Sticker]({summary['top_sticker_url']}) (Top 1) | |

*(注：数据完全在本地计算，保障隐私安全)*

**Generated by Project MemoryLane**
"""
    
    # Write to file
    with open(OUTPUT_REPORT, "w", encoding="utf-8") as f:
        f.write(md)
        
    print(f"Report assembled: {OUTPUT_REPORT}")

if __name__ == "__main__":
    generate_markdown()
